#! /bin/sh

sxhkd &

########################################################################
#                            M O N I T O R S                           #
########################################################################

xrandr --output HDMI-1 --primary --left-of eDP-1 --size 1920x1080 &

bspc subscribe monitor | while read -r line; do
  case $line in
      monitor_add*|monitor_geometry*)
	if [[ "$(xrandr | grep -w "HDMI-1 connected")" == *"HDMI-1 connected"* ]] 
	then          
        bspc monitor eDP-1 -d " 8" " 9" " 0"
		bspc monitor HDMI-1 -d " 1" " 2" " 3" " 4" " 5" " 6" " 7"
        
	elif [[ "$(xrandr | grep -w "DP-1 connected"  )" == *"DP-1 connected"* ]] 
        then
                bspc monitor eDP-1 -d " 1" " 2" " 3" " 4" " 5" " 6" " 7"
                bspc monitor DP-1 -d " 8" " 9" " 0"
	else
          	bspc monitor -d "I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "X"
        fi
        ;;
      *)
      ;;
  esac
done &

#bspc wm --adopt-orphans

########################################################################
#                           A U T O S T A R T                          #
########################################################################

~/.config/polybar/launch.sh &

########################################################################
#                         A P P E A R A N C E                          #
########################################################################


bspc config border_width         2
bspc config window_gap           3
#bspc config top_padding          27

bspc config normal_border_color "#44475a"
bspc config active_border_color "#44475a"
bspc config focused_border_color "#5c64a1"
bspc config presel_feedback_color "#6272a4"

mark-ovredir-focused = false

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

########################################################################
#                              R U L E S                               #
########################################################################

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a spotify desktop='^10'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

bspc config pointer_modifier mod4 # mod4 = super key
bspc config pointer_action1 move # super + left click
bspc config pointer_action2 resize_corner # super + right click
